In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
import pandas as pd
import spacy

In [40]:
# Load the raw data
df = pd.read_excel("/content/drive/MyDrive/group5_p2.1/group5_raw_data/restaurant_reviews-v2-1.xlsx")
df.head()

,Restaurant,Review,Real=1/Fake=0,positive=1/negative=0,AWL,ASL,NOW,NVB,NAJ,NPV,NST,CDV,NTP,TPR
0,Tikka Shack,Great food and great atmosphere! The chicken t...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tikka Shack,I had heard good things about Tikka Shak so I ...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tikka Shack,I was driving by tikka shack one day and decid...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tikka Shack,Tikka Shack had the most modern and up-to-date...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,India Palace\nIndian\nRestaurant,Today is the third time I've come to India Pal...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Drop restaurant column and positive/negative column
review_df = df.drop(columns=['Restaurant', 'positive=1/negative=0'])

num_rows = review_df.shape[0]
num_cols = review_df.shape[1]

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

review_df.head()

Number of rows: 260
Number of columns: 12

,Review,Real=1/Fake=0,AWL,ASL,NOW,NVB,NAJ,NPV,NST,CDV,NTP,TPR
0,Great food and great atmosphere! The chicken t...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I had heard good things about Tikka Shak so I ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I was driving by tikka shack one day and decid...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tikka Shack had the most modern and up-to-date...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Today is the third time I've come to India Pal...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN